/* MOSTRAR NÚMEROS PARES E NÚMEROS IMPARES DE 1 A 10*/
console.log('Números Pares:')
console.log(0)
console.log(2)
console.log(4)
console.log(6)
console.log(8)
console.log(10)

console.log('Números Ímpares:')
console.log(1)
console.log(3)
console.log(5)
console.log(7)
console.log(9)